# Generated by Django 3.0.1 on 2022-05-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_follower_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
