# Generated by Django 3.0.1 on 2022-05-22 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='savers',
            field=models.ManyToManyField(blank=True, null=True, related_name='savers', to=settings.AUTH_USER_MODEL),
        ),
    ]
