# Generated by Django 3.0.1 on 2022-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_savers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='media/profile_pic/'),
        ),
    ]
