# Generated by Django 3.0.1 on 2022-05-26 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20220526_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='savers',
            field=models.ManyToManyField(blank=True, related_name='savers', to=settings.AUTH_USER_MODEL),
        ),
    ]
